import '../../../../Model/question_model.dart';

final List<QuestionModel> mathQuestions = [
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "What is the value of pi (π) to the nearest thousandth?",
    "3.142",
    ["3.14", "3.141", "3.1416"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "If a train travels 60 miles per hour and departs at 2:00 PM, what time will it arrive at its destination 180 miles away?",
    "5:00 PM",
    ["4:00 PM", "6:00 PM", "7:00 PM"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "What is the square root of 81?",
    "9",
    ["7", "8", "10"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "Solve for x: 3x + 7 = 22",
    "5",
    ["4", "6", "8"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "What is the area of a rectangle with length 8 units and width 5 units?",
    "40 square units",
    ["13 square units", "30 square units", "45 square units"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "Simplify: (2 + 5) * 3 - 4",
    "21",
    ["15", "18", "27"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "If the radius of a circle is 6 units, what is its circumference? (Use π = 3.14)",
    "37.68 units",
    ["12.56 units", "18.84 units", "75.36 units"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "Find the value of 'a' in the equation: 4a + 9 = 37",
    "7",
    ["6", "8", "10"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "A store is offering a 20% discount on all items. If the original price of a book is 25, what is the discounted price?",
    "20",
    ["15", "18", "22"],
  ),
  QuestionModel(
    "Math",
    "multiple_choice",
    "medium",
    "If a person can paint a room in 6 hours, how many people are needed to paint the same room in 2 hours?",
    "9 people",
    ["3 people", "6 people", "12 people"],
  ),
];
