import '../../../../Model/question_model.dart';

final List<QuestionModel> physicsQuestions = [
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "What is the SI unit of force?",
    "Newton (N)",
    ["Joule (J)", "Watt (W)", "Kilogram (kg)"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "What is the acceleration due to gravity on Earth (approximately)?",
    "9.81 m/s²",
    ["6.63 m/s²", "10.25 m/s²", "12.50 m/s²"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "Which law of motion states that 'for every action, there is an equal and opposite reaction'?",
    "Newton's third law",
    ["Newton's first law", "Newton's second law", "Einstein's law"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "What is the term for the energy possessed by an object due to its motion?",
    "Kinetic energy",
    ["Potential energy", "Thermal energy", "Electrical energy"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "Which type of waves are used in radar and microwave ovens?",
    "Microwaves",
    ["Ultraviolet waves", "Radio waves", "Infrared waves"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "What is the process of converting a solid directly to a gas without passing through the liquid state?",
    "Sublimation",
    ["Evaporation", "Condensation", "Melting"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "What is the unit of electric charge?",
    "Coulomb (C)",
    ["Volt (V)", "Ampere (A)", "Ohm (Ω)"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "What is the phenomenon where a wave bends as it passes through a medium with different propagation speed?",
    "Refraction",
    ["Reflection", "Diffraction", "Interference"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "According to the theory of relativity, as an object's speed approaches the speed of light, its mass...",
    "Increases",
    ["Decreases", "Remains constant", "Becomes zero"],
  ),
  QuestionModel(
    "Physics",
    "multiple_choice",
    "medium",
    "What is the resistance of an object to changes in its rotational motion?",
    "Moment of inertia",
    ["Angular velocity", "Centripetal force", "Angular momentum"],
  ),
];
