import '../../../../Model/question_model.dart';

final List<QuestionModel> scienceQuestions = [
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "What is the chemical symbol for water?",
    "H2O",
    ["CO2", "O2", "NaCl"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "Which planet in our solar system is known as the 'Red Planet'?",
    "Mars",
    ["Venus", "Jupiter", "Saturn"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "What is the unit of measurement for electric current?",
    "Ampere (A)",
    ["Volt (V)", "Watt (W)", "Ohm (Ω)"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "What is the process by which plants make their own food?",
    "Photosynthesis",
    ["Respiration", "Fermentation", "Transpiration"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "Which gas is most abundant in Earth's atmosphere?",
    "Nitrogen (N2)",
    ["Oxygen (O2)", "Carbon dioxide (CO2)", "Argon (Ar)"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "What is the smallest unit of matter?",
    "Atom",
    ["Molecule", "Element", "Compound"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "Which type of electromagnetic radiation has the shortest wavelength?",
    "Gamma rays",
    ["X-rays", "Ultraviolet rays", "Microwaves"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "What causes tides on Earth?",
    "Gravitational pull of the Moon",
    ["Gravitational pull of the Sun", "Earth's rotation", "Winds"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "What type of rock is formed by the cooling of lava?",
    "Igneous rock",
    ["Metamorphic rock", "Sedimentary rock", "Volcanic rock"],
  ),
  QuestionModel(
    "Science",
    "multiple_choice",
    "medium",
    "What is the function of the mitochondria in a cell?",
    "Energy production",
    ["Protein synthesis", "Cell division", "Storage of genetic information"],
  ),
];
