import '../../../../Model/question_model.dart';

final List<QuestionModel> animalsAndWildlifeQuestions = [
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "What is the largest species of penguin?",
    "Emperor Penguin",
    ["King Penguin", "Adélie Penguin", "Gentoo Penguin"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "Which big cat is known for its distinctive black mane and is often called the 'King of the Jungle'?",
    "Lion",
    ["Tiger", "Leopard", "Cheetah"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "What is the tallest land animal in the world?",
    "Giraffe",
    ["Elephant", "Hippopotamus", "Kangaroo"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "Which bird species is famous for its courtship dance involving vibrant plumage and elaborate displays?",
    "Peacock",
    ["Flamingo", "Penguin", "Ostrich"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "What is the largest species of bear?",
    "Polar Bear",
    ["Grizzly Bear", "Kodiak Bear", "Brown Bear"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "Which marine mammal is known for its loud songs and complex social behavior?",
    "Humpback Whale",
    ["Dolphin", "Killer Whale (Orca)", "Blue Whale"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "What is the national animal of China and a symbol of strength and power?",
    "Giant Panda",
    ["Red Panda", "Snow Leopard", "Golden Monkey"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "Which venomous snake is known for its hood-like markings and is found in various parts of Asia and Africa?",
    "King Cobra",
    ["Rattlesnake", "Black Mamba", "Inland Taipan"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "Which marsupial is native to Australia and known for carrying its young in a pouch?",
    "Kangaroo",
    ["Koala", "Wombat", "Tasmanian Devil"],
  ),
  QuestionModel(
    "Animals and Wildlife",
    "multiple_choice",
    "medium",
    "What is the fastest land animal in the world?",
    "Cheetah",
    ["Lion", "Leopard", "Tiger"],
  ),
];
