import '../../../../Model/question_model.dart';

List<QuestionModel> mythologyQuestions = [
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "Who was the king of the gods in ancient Greek mythology?",
    "Zeus",
    ["Hades", "Poseidon", "Apollo"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "In Norse mythology, which god is known as the 'All-Father' and ruler of Asgard?",
    "Odin",
    ["Thor", "Loki", "Freyr"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "According to Hindu mythology, who is the preserver and protector of the universe?",
    "Vishnu",
    ["Shiva", "Brahma", "Krishna"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "In Egyptian mythology, who is the god of the afterlife and the judge of the dead?",
    "Osiris",
    ["Ra", "Anubis", "Horus"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "Which figure from Arthurian legend was the court magician of King Arthur?",
    "Merlin",
    ["Lancelot", "Gawain", "Guinevere"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "In Japanese mythology, what are the names of the sun goddess and the storm god, respectively?",
    "Amaterasu and Susanoo",
    ["Izanami and Izanagi", "Hachiman and Raijin", "Tsukuyomi and Fujin"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "Which monster from Greek mythology had snakes for hair and could turn people to stone with her gaze?",
    "Medusa",
    ["Cyclops", "Siren", "Hydra"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "In Norse mythology, what is the name of the mythical sword that can kill the great serpent Jörmungandr?",
    "Mjölnir",
    ["Gungnir", "Tyrfing", "Excalibur"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "According to Aztec mythology, which god was associated with the sun?",
    "Huitzilopochtli",
    ["Quetzalcoatl", "Tlaloc", "Tezcatlipoca"],
  ),
  QuestionModel(
    "Mythology",
    "multiple_choice",
    "medium",
    "Which figure from Chinese mythology is often depicted as a monkey and possesses immense strength?",
    "Sun Wukong (The Monkey King)",
    ["Zhu Bajie", "Nezha", "Jiang Ziya"],
  ),
];
