import '../../../../Model/question_model.dart';

final List<QuestionModel> geographyQuestions = [
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "What is the longest river in the world?",
    "Nile River",
    ["Amazon River", "Yangtze River", "Mississippi River"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "Which desert is the largest in the world?",
    "Sahara Desert",
    ["Arabian Desert", "Gobi Desert", "Kalahari Desert"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "Which country is known as the 'Land of the Rising Sun'?",
    "Japan",
    ["China", "South Korea", "Thailand"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "Which mountain range runs along the southern border of China?",
    "Himalayas",
    ["Andes", "Rocky Mountains", "Alps"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "Which continent is the largest by land area?",
    "Asia",
    ["Africa", "North America", "South America"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "What is the capital city of Australia?",
    "Canberra",
    ["Sydney", "Melbourne", "Perth"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "Which ocean is the largest on Earth?",
    "Pacific Ocean",
    ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "The Great Barrier Reef, one of the world's largest coral reef systems, is located off the coast of which country?",
    "Australia",
    ["Brazil", "India", "Philippines"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "What is the capital city of Canada?",
    "Ottawa",
    ["Toronto", "Vancouver", "Montreal"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "medium",
    "Which African country is known as the 'Pearl of Africa'?",
    "Uganda",
    ["Kenya", "Tanzania", "Rwanda"],
  ),
];
