import '../../../../Model/question_model.dart';

final List<QuestionModel> Geography2Questions = [
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "Which country is the smallest in the world by land area?",
    "Vatican City",
    ["Monaco", "Nauru", "Maldives"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "Which two countries share the longest international land border in the world?",
    "Canada and the United States",
    ["China and Russia", "India and Pakistan", "Argentina and Chile"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "What is the driest desert in the world?",
    "Atacama Desert",
    ["Namib Desert", "Arabian Desert", "Kalahari Desert"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "Which strait separates Asia from North America?",
    "Bering Strait",
    ["Strait of Gibraltar", "Strait of Hormuz", "Strait of Malacca"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "Which river is the longest in South America?",
    "Amazon River",
    ["Orinoco River", "Magdalena River", "Paraná River"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "The city of Istanbul is located on two continents. Which continents does it straddle?",
    "Europe and Asia",
    ["Africa and Asia", "Europe and Africa", "Asia and Australia"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "Which mountain is the highest in Africa?",
    "Mount Kilimanjaro",
    ["Mount Everest", "Mount McKinley", "Mount Aconcagua"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "The Gobi Desert spans across which two countries?",
    "Mongolia and China",
    [
      "Kazakhstan and Uzbekistan",
      "Iran and Afghanistan",
      "Saudi Arabia and Jordan"
    ],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "Which island group in the Pacific Ocean is known for its unique statues called 'moai'?",
    "Easter Island (Rapa Nui)",
    ["Galápagos Islands", "Fiji Islands", "Solomon Islands"],
  ),
  QuestionModel(
    "Geography",
    "multiple_choice",
    "hard",
    "The Maldives, an island nation, is located in which ocean?",
    "Indian Ocean",
    ["Pacific Ocean", "Atlantic Ocean", "Arctic Ocean"],
  ),
];
