import '../../../../Model/question_model.dart';

final List<QuestionModel> history2Questions = [
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "Which treaty formally ended World War I?",
    "Treaty of Versailles",
    ["Treaty of Tordesillas", "Treaty of Ghent", "Treaty of Brest-Litovsk"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "Who was the last Aztec emperor who was captured and killed by the Spanish conquistadors?",
    "Montezuma II",
    ["Atahualpa", "Moctezuma I", "Cuauhtémoc"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "Which Chinese philosopher and founder of Confucianism emphasized the importance of ethics, family values, and moral integrity?",
    "Confucius",
    ["Laozi", "Mencius", "Sun Tzu"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "Which ancient civilization built the city of Machu Picchu in the Andes Mountains?",
    "Inca",
    ["Maya", "Aztec", "Sumerian"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "The Opium Wars, fought between China and which European country, led to the cession of Hong Kong?",
    "Britain",
    ["France", "Portugal", "Spain"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "Who was the Roman general and statesman who led the conquest of Gaul and later became the dictator of Rome?",
    "Julius Caesar",
    ["Augustus", "Hannibal", "Cicero"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "Which pharaoh is known for promoting the worship of Aten, the sun disc, and briefly shifting Egypt to monotheism?",
    "Akhenaten",
    ["Ramses II", "Cleopatra VII", "Hatshepsut"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "In 1066, the Battle of Hastings resulted in the victory of which Norman leader over King Harold II of England?",
    "William the Conqueror",
    ["Richard the Lionheart", "Harald Hardrada", "Edward the Confessor"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "Which historical event marked the beginning of the French Revolution?",
    "Storming of the Bastille",
    ["Reign of Terror", "Battle of Waterloo", "Tennis Court Oath"],
  ),
  QuestionModel(
    "History",
    "multiple_choice",
    "hard",
    "The Boxer Rebellion, an anti-foreign and anti-Christian uprising, occurred in which country?",
    "China",
    ["India", "Japan", "Korea"],
  ),
];
