// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBvOPzSxh6j1pltIbcGK2_JKUocXzKJNE',
    appId: '1:994520732843:web:173d344870e6977b0f13ee',
    messagingSenderId: '994520732843',
    projectId: 'quizz-dab34',
    authDomain: 'quizz-dab34.firebaseapp.com',
    storageBucket: 'quizz-dab34.appspot.com',
    measurementId: 'G-XVQFWVGMSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtARBb6UWyTqSC-meKyr8Ap1jxm76PatI',
    appId: '1:994520732843:android:8d2b98d25858f8c70f13ee',
    messagingSenderId: '994520732843',
    projectId: 'quizz-dab34',
    storageBucket: 'quizz-dab34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLI2SGY8buA0oRbcUV3WWWvZLr04ch9c',
    appId: '1:994520732843:ios:85113e6ed30288de0f13ee',
    messagingSenderId: '994520732843',
    projectId: 'quizz-dab34',
    storageBucket: 'quizz-dab34.appspot.com',
    iosClientId: '994520732843-oher8kf8f7r3ku08235q7a3r6dphgbhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXLI2SGY8buA0oRbcUV3WWWvZLr04ch9c',
    appId: '1:994520732843:ios:11acd2285945bfde0f13ee',
    messagingSenderId: '994520732843',
    projectId: 'quizz-dab34',
    storageBucket: 'quizz-dab34.appspot.com',
    iosClientId: '994520732843-2n0dm8n3cbaovfjg74onvdfg5jlsqv69.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz.RunnerTests',
  );
}
